// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // configurations per platform
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLduy2r7emeXN9U3rL_kS7ij6BrCwP6SY',
    appId: '1:199802988376:web:415237efc85f074d74672d',
    messagingSenderId: '199802988376',
    projectId: 'cmsc23-week8-data-persistence',
    authDomain: 'cmsc23-week8-data-persistence.firebaseapp.com',
    storageBucket: 'cmsc23-week8-data-persistence.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpowPkINzmMXTqNP87mtpyOSkWuKethE',
    appId: '1:199802988376:android:2126c7949bfe842074672d',
    messagingSenderId: '199802988376',
    projectId: 'cmsc23-week8-data-persistence',
    storageBucket: 'cmsc23-week8-data-persistence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtio7DiCJNWRv02lOnUHXeKlYnAIC7Khg',
    appId: '1:199802988376:ios:98d2d884c63200b774672d',
    messagingSenderId: '199802988376',
    projectId: 'cmsc23-week8-data-persistence',
    storageBucket: 'cmsc23-week8-data-persistence.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtio7DiCJNWRv02lOnUHXeKlYnAIC7Khg',
    appId: '1:199802988376:ios:98d2d884c63200b774672d',
    messagingSenderId: '199802988376',
    projectId: 'cmsc23-week8-data-persistence',
    storageBucket: 'cmsc23-week8-data-persistence.appspot.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLduy2r7emeXN9U3rL_kS7ij6BrCwP6SY',
    appId: '1:199802988376:web:c6acb02beca4547674672d',
    messagingSenderId: '199802988376',
    projectId: 'cmsc23-week8-data-persistence',
    authDomain: 'cmsc23-week8-data-persistence.firebaseapp.com',
    storageBucket: 'cmsc23-week8-data-persistence.appspot.com',
  );
}
